name: Start CRD Session with Extended Pending Step

on:
  workflow_dispatch:

jobs:
  setup_crd:
    runs-on: ubuntu-latest

    steps:
      - name: Install Chrome Browser
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Chrome Remote Desktop
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt install -y ./chrome-remote-desktop_current_amd64.deb
          sudo apt install -y xfce4 xfce4-goodies

      - name: Ensure CRD Configuration Directory
        run: |
          mkdir -p /home/runner/.config/chrome-remote-desktop
          chmod 700 /home/runner/.config/chrome-remote-desktop

      - name: Start CRD Session
        env:
          CRD_AUTH_CODE: ${{ secrets.CRD_AUTH_CODE }}
          CRD_PIN: "123456"  # Sesuaikan dengan PIN yang Anda tetapkan
        run: |
          DISPLAY=:0 /opt/google/chrome-remote-desktop/start-host --code="$CRD_AUTH_CODE" --name="GitHubActionsUbuntu" --pin="$CRD_PIN" &
          echo "Chrome Remote Desktop session initiated with PIN."

      - name: Pending Step (Sleep for 6 Hours)
        run: |
          echo "Pending for 6 hours to keep session active..."
          sleep 21600  # 6 jam dalam detik
