name: Setup Chrome Remote Desktop on Ubuntu

on:
  workflow_dispatch:

jobs:
  setup_crd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chrome Browser
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt update
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Chrome Remote Desktop
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt install -y ./chrome-remote-desktop_current_amd64.deb
          sudo apt install -y xfce4 xfce4-goodies  # XFCE4 sebagai desktop environment

      - name: Ensure CRD Configuration Directory
        run: |
          mkdir -p /home/runner/.config/chrome-remote-desktop
          chmod 700 /home/runner/.config/chrome-remote-desktop

      - name: Setup Chrome Remote Desktop Session
        env:
          CRD_AUTH_CODE: ${{ secrets.CRD_AUTH_CODE }}
          CRD_PIN: "123456"  # Sesuaikan PIN ini
        run: |
          DISPLAY=:0 /opt/google/chrome-remote-desktop/start-host --code="$CRD_AUTH_CODE" --name="GitHubActionsUbuntu" --pin="$CRD_PIN" &
          echo "Chrome Remote Desktop session initiated with PIN."

      - name: Display Connection Instructions
        run: |
          echo "Chrome Remote Desktop setup complete. Access this session by signing in to https://remotedesktop.google.com/access with your Google account and selecting 'GitHubActionsUbuntu'."
