name: Setup Chrome Remote Desktop on Ubuntu

on:
  workflow_dispatch:

jobs:
  setup_crd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chrome Browser
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt update
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Chrome Remote Desktop
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt install -y ./chrome-remote-desktop_current_amd64.deb
          sudo apt install -y xfce4 xfce4-goodies  # XFCE4 sebagai desktop environment

      - name: Setup Chrome Remote Desktop Session
        env:
          CRD_AUTH_CODE: ${{ secrets.CRD_AUTH_CODE }}
        run: |
          # Mengaktifkan Chrome Remote Desktop dengan kode otorisasi dari CRD_AUTH_CODE
          DISPLAY=:0 /opt/google/chrome-remote-desktop/start-host --code="$CRD_AUTH_CODE" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="GitHubActionsUbuntu" &

      - name: Display Connection Instructions
        run: |
          echo "Chrome Remote Desktop setup complete. Access this session by signing in to https://remotedesktop.google.com/access with your Google account and selecting 'GitHubActionsUbuntu'."
